name: "[CI] verify debug build test"

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - main
      - develop

jobs:
  build_test:
    environment: Debug
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle_command:
          - :app:assembleDebug
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Development Environment
        uses: ./.github/actions/setup-development-environment
        with:
          google-services: ${{ secrets.GOOGLE_SERVICES }}
          test-mode: debug
          debug-properties: ${{ secrets.DEBUG_PROPERTIES }}

      - name: build test
        run: ./gradlew ${{ matrix.gradle_command }}