name: "[CI] verify build test"

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - develop
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle_command:
          - :app:assembleRelease
          - :app:assembleDebug
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Development Environment
        uses: ./.github/actions/setup-development-environment
        with:
          google-services: ${{ secrets.GOOGLE_SERVICES }}
          test-mode: ${{ github.base_ref == 'develop' && 'debug' || 'release' }}
          debug-properties: ${{ secrets.DEBUG_PROPERTIES }}
          if: github.base_ref == 'main'
          release-properties: ${{ secrets.RELEASE_PROPERTIES  }}

      - name: build test
        run: ./gradlew ${{ matrix.gradle_command }}