name: Verify Preview Screenshot

on:
  push:

jobs:
  build-gradle-project:
    environment: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Setup Development Environment
        uses: ./.github/actions/setup-development-environment
        with:
          google-services: ${{ secrets.GOOGLE_SERVICES }}
          test-mode: debug
          debug-properties: ${{ secrets.DEBUG_PROPERTIES }}

      - name: Setup Signed Key Environment
        uses: ./.github/actions/setup-key-environment
        with:
          key-properties: ${{ secrets.KEY_PROPERTIES }}
          key-file: ${{ secrets.SIGNED_KEY }}

      - name: Checkout Previous Commit
        run: git checkout HEAD^

      - name: Run updateDebugScreenshotTest
        run: ./gradlew updateDebugScreenshotTest

      - name: Checkout Latest Commit
        run: git checkout -

      - name: Run validateDebugScreenshotTest
        run: ./gradlew validateDebugScreenshotTest

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: my-artifact
          path: presentation/build/reports