name: "[CI] verify build test"

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - develop
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle_command:
          - :app:assembleRelease
          - :app:assembleDebug
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Development Environment
        uses: ./.github/actions/setup-development-environment
        with:
          google-services: ${{ secrets.GOOGLE_SERVICES }}

      - name: build test
        run: ./gradlew ${{ matrix.gradle_command }}